
services:
    db:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=admin123
          - POSTGRES_USER=admin
          - POSTGRES_DB=pricealert_db
        
    redis:
        image:  redis:7-alpine
        ports:  
          - "6379:6379"
